components/speaker/MostSearchedSpeakers.tsx
pages/index.tsx

Add most searched speakers section.

Add most searched speakers section

---

components/SearchResultSpeaker.tsx
components/pagination.tsx
libs/pluralize.ts
pages/vyhledavani/politici.tsx

Implements search of speakers (politicians).

Add searching of speakers

---

components/statement/Item.tsx
pages/vyhledavani/index.tsx
pages/vyhledavani/vyroky.tsx

Add statement search and extended statement search results.

Add statement search

---

pages/index.tsx

Add banner about workshops to the homepage

Add workshop section to the homepage

---

pages/vyhledavani/politici.tsx

Add president and governmental speakers to the API

Add president and governmental speakers

---

next.config.js
pages/o-nas/index.tsx

List members on the about us page.

List demagog member on the about us page

---

components/filtering/FilterForm.tsx
components/filtering/ResetFilters.tsx
package-lock.json
package.json

Add automatic form submit on filter change after 1 sec

---

components/speaker/SpeakerWithStats.tsx

Dynamic classes in the speaker stats.

Dynamic classes in speaker stats

---

components/site/Header.tsx
pages/_app.tsx
pages/index.tsx

Also adds workshops to the navigation

Update main site page title

---

components/article/Tags.tsx
pages/spoluprace-s-facebookem/index.tsx
pages/tag/[slug].tsx

Adds is tag detail open prop to the tags component. When it's true we'll show the back button.

Show back button on tag detail

---

components/site/Newsletter.tsx

Replace footer section with newsletter by whatsapp.

Add whatsapp banner instead of newsletter

---

pages/workshopy/index.tsx

Add call to action (send order by e-mail) to order a workshop.

Add call to action on workshops page

---

components/speaker/Item.tsx
components/speaker/SpeakerLink.tsx
libs/query-params.tsx
pages/politici/[id].tsx
pages/vypis-recniku/index.tsx

Generate seo friendly URLs in the app.

Use slugs instead of ids for speakers

---

.github/workflows/node.js.yml

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group

Run jobs on merge queue

---

app/articles/[slug]/page.tsx
app/page.tsx
app/promises/[slug]/page.tsx
app/search/page.tsx
app/search/search-articles/page.tsx
app/search/search-speakers/page.tsx
app/search/search-statements/page.tsx
app/speakers/[slug]/page.tsx
app/speakers/page.tsx
app/statements/page.tsx
app/tags/[slug]/page.tsx
app/tags/facebook/page.tsx
app/workshops/page.tsx
libs/params.ts

Explained https://github.com/Demagog2/demagog-frontend/issues/141

Unify page definitions

---

components/homepage/HomepageFirstPage.tsx
components/homepage/HomepageNextPage.tsx
components/site/Navigation.tsx

Fix pagination margin under homepage articles

---

components/article/Article.tsx
components/article/Item.tsx
components/article/SingleStatementArticlePreview.tsx

See https://github.com/Demagog2/demagog-frontend/issues/79

Show alternative background for pinned articles

---

components/article/FacebookFactcheckFirstPage.tsx
components/site/HomeSidebar.tsx
components/util/Expander.tsx

Re-implemented expander controller from the original website to React.

Fold info panels on mobile

---

app/(main)/speakers/[slug]/page.tsx

Fixes https://demagog.sentry.io/share/issue/7f99be37a99f45fe8d07a2551f31cdd1/

Fix filter input name

---

app/(admin)/admin/articles/new/page.tsx
components/admin/articles/AdminArticleForm.tsx
components/admin/articles/AdminSourcesList.tsx
next.config.js

Add source segment selection

---

components/admin/articles/AdminArticleForm.tsx
components/admin/articles/AdminSegmentSelector.tsx

Make the segment selector a bit nicer.

Add segment type selector

---

app/(admin)/admin/articles/[slug]/edit/page.tsx
app/(admin)/admin/articles/actions.ts
components/admin/articles/AdminArticleForm.tsx
components/admin/articles/AdminArticleHeader.tsx
libs/articles/schema.ts

Allows editing of articles except for the article illustration (image), that requires BE changed planned here https://github.com/Demagog2/demagog/issues/1307

Edit article page

---

app/(admin)/admin/tags/page.tsx
components/admin/AdminClientLayout.tsx

Add admin tags page

---

app/(admin)/admin/sources/page.tsx
components/admin/AdminClientLayout.tsx
libs/constants/assessment.ts

Add sources listing to the admin

---

app/(admin)/admin/tags/page.tsx

* allows for search
* allows for relay style (cursor based) pagination

Use tags v2 GraphQL API

---

app/(admin)/admin/sources/page.tsx
components/admin/UserMenu.tsx

I've added full name field to the API, so we don't have to concatenate the strings manually.
cc @zuzubel.
Close #235 
Close #233

Use user full name and avatar size

---

app/(admin)/admin/tags/actions.ts
app/(admin)/admin/tags/new/page.tsx
app/(admin)/admin/tags/page.tsx
components/admin/tags/AdminTagForm.tsx
libs/tags/schema.ts

Add new tag page and form

---

assets/styles/tailwind.css
components/admin/articles/AdminArticleForm.tsx
components/admin/forms/RichTextEditor.tsx
package-lock.json
package.json

Use rich text editor for text segments

---

app/(admin)/admin/articles/page.tsx
app/(admin)/admin/tags/page.tsx
components/admin/AdminPagination.tsx

This is what we've done this morning together @zuzubel

Admin pagination refactor

---

app/(admin)/admin/sources/page.tsx

~TODO: Add admin pagination~ ✅

Add pagination to discussions

---

components/admin/articles/AdminArticleForm.tsx

Works for creating and updating articles.

Add article tags multiselect

---

components/admin/articles/AdminArticleDeleteDialog.tsx
components/admin/articles/AdminArticleHeader.tsx

Add remove button to the article detail

---

components/admin/articles/AdminArticleIllustrationDialog.tsx
components/admin/articles/AdminArticleSingleStatementForm.tsx
components/admin/forms/SubmitButton.tsx
libs/api.ts
libs/articles/article-illustration-schema.ts

Generate image from tweet dialog

---

components/article/FacebookFactcheckFirstPage.tsx
components/homepage/HomepageFirstPage.tsx
components/site/DonateWidget.tsx

Also renamed donate sidebar to donate widget.

Use donate widget on FB and tag first pages

---

components/admin/forms/RichTextEditor.tsx

Add image captions to the image toolbar

---

app/(admin)/admin/articles/[slug]/edit/page.tsx
app/(admin)/admin/articles/new-single-statement/page.tsx
app/(admin)/admin/articles/new/page.tsx
components/admin/articles/AdminArticleForm.tsx
components/admin/articles/AdminArticleSingleStatementForm.tsx
components/admin/layout/AdminFormHeader.tsx
components/admin/layout/AdminPageTitle.tsx

Move buttons above create article forms

---

app/(admin)/beta/admin/sources/[slug]/page.tsx
components/admin/sources/AdminSourceHeader.tsx
components/admin/sources/AdminSourceStatements.tsx
components/admin/sources/AdminSourcesFilters.tsx

* Adds page title
* Fixes link to speaker
* Fixes link to edit page

Source detail update

---

package-lock.json

Reverts Demagog2/demagog-frontend#459

Revert "Bump @hookform/resolvers from 3.9.0 to 3.9.1"

---

package-lock.json

Reverts Demagog2/demagog-frontend#483

Revert "Revert "Bump @hookform/resolvers from 3.9.0 to 3.9.1""

---

package-lock.json

Reverts Demagog2/demagog-frontend#484

Revert "Revert "Bump @sentry/nextjs from 8.35.0 to 8.36.0""

---

components/article/ArticleSegments.tsx

- added statementNode and textNode into the query
- created loop showing text segments and statement segments

Article displaying from new api

---

components/admin/articles/segments/AdminStatement.tsx
libs/ck-plugins/embed-statement.spec.ts
libs/ck-plugins/embed-statement.tsx
libs/ck-plugins/utils/parse-id.spec.ts
libs/ck-plugins/utils/parse-id.ts

Fix embedding statement with broken ID

---

assets/styles/tailwind.css
components/admin/articles/AdminArticleItem.tsx
components/admin/articles/AdminSingleStatementArticlePreview.tsx

- changed both types of embedded articles (single statement and article item)

Changed styling of  embedded articles in admin according figma

---

app/(main)/articles/[slug]/redesign/page.tsx
components/admin/articles/AdminArticleContent.tsx
components/admin/forms/RichTextEditor.tsx
components/article/ArticleQuoteRedesign.tsx
components/article/ArticleSegments.tsx

Article redesign - Use block quote component

---

app/(admin)/beta/admin/articles/[slug]/redesign/page.tsx
assets/styles/tailwind.css
components/admin/articles/AdminArticleContent.tsx
components/admin/articles/AdminArticleQuote.tsx

+ added speaker design into quote in article content

Created redesign page for articles in admin

---

assets/styles/tailwind.css
components/admin/forms/RichTextEditor.tsx
libs/ck-plugins/box/box-command.ts
libs/ck-plugins/box/box.ts
libs/ck-plugins/utils/containers.ts

Add possibility to define summary via CK Editor

---

app/(main)/page.tsx

Reverts Demagog2/demagog-frontend#633

Revert "Attempt enforcing ISR for homepage"

---

assets/styles/tailwind.css
components/admin/articles/AdminArticleItem.tsx
components/admin/articles/AdminSingleStatementArticlePreview.tsx
components/admin/forms/RichTextEditor.tsx
libs/ck-plugins/box/box-toggle-bg-command.ts
libs/ck-plugins/box/box-toggle-float-command.ts
libs/ck-plugins/box/box-toolbar.ts
libs/ck-plugins/box/box.ts
libs/ck-plugins/utils/containers.ts

https://github.com/user-attachments/assets/b85df89d-9542-41f7-87f2-0725b0df7b87

Show toggle float and grey bg via toolbar

---

assets/styles/tailwind.css

Add h3 styles for CK editor and admin article detail

---

app/(main)/statements/[slug]/redesign/page.tsx

Also changed conditions for displaying the "Výrok jsme zmínili" heading. Now it appears only when there is any mentioning article

Created statement detail redesign page

---

components/admin/forms/Multiselect.tsx
components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/controls/AdminTagsMultiselect.tsx
libs/sources/statement-schema.ts

Add selection of statements tags

---

components/admin/sources/statements/AdminAssessmentForm.tsx
libs/sources/statement-schema.ts

Add statement content field

---

app/(admin)/beta/admin/sources/actions.ts
components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/controls/AdminPromiseRatingSelect.tsx
libs/sources/machines/assessment-process-machine.ts
libs/sources/statement-schema.ts

Add assessment promise rating

---

app/(main)/statements/[slug]/redesign/page.tsx
assets/styles/main.scss
assets/styles/statement/_redesign.scss

- Removed "Short explanation" heading
- created and imported new scss file for statement redesign
- body symbol size changed according to figma

Removed heading, created scss file, changed size of body symbol

---

app/(admin)/beta/admin/sources/actions.ts
components/admin/sources/statements/AdminAssessmentForm.tsx
libs/sources/statement-schema.ts

Add statement assessment explanation field

---

components/admin/articles/AdminArticleForm.tsx
components/admin/forms/SwitchField.tsx
components/admin/layout/AdminFormMain.tsx
components/admin/layout/AdminFormSidebar.tsx
components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/hooks/statement-evaluation-machine.ts
libs/sources/assessment-schema.ts
libs/sources/machines/assessment-process-machine.ts

Add statement published switch

---

app/(main)/speakers/[slug]/page.tsx
app/(main)/statements/[slug]/page.tsx
components/statement/Assessment.tsx
components/statement/Item.tsx
components/statement/SourceSpeakerAvatar.tsx

Use fw-bold and fw-600 instead of non-existing classes

---

components/statement/Item.tsx

Explained at https://github.com/Demagog2/demagog-frontend/issues/713

Replace non-existant fs-8 with fs-3

---

components/admin/sources/AdminSourceStatementStep.tsx
components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/AdminExpertsList.tsx
components/admin/sources/statements/controls/AdminEvaluationStatusControl.tsx

Show evaluation progress on statement detail

---

components/admin/sources/AdminSourceStatements.tsx

https://github.com/user-attachments/assets/b8c9c810-bdb2-4640-a230-b90342fb5c26

Make the whole statement as a button

---

assets/styles/tailwind.css
components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/AdminStatementComments.tsx
libs/comments/text.ts

Display statement comments in statement detail

---

assets/styles/article/_redesign.scss
assets/styles/campaign.scss
assets/styles/campaign/styles.module.css
assets/styles/core/_base.scss
assets/styles/homepage/index.scss
assets/styles/responsive/font-size.scss
assets/styles/speaker/show.scss
assets/styles/statement/_redesign.scss
components/article/ArticleQuoteRedesign.tsx

Closes https://github.com/Demagog2/demagog-frontend/issues/753

Re-use fs-2 wherever possible

---

components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/controls/AdminTagsMultiselect.tsx

Closes https://github.com/Demagog2/demagog-frontend/issues/817

Fix statement tags placeholder and remove optional label

---

app/(admin)/beta/admin/sources/actions.ts
components/admin/sources/statements/AdminStatementForm.tsx
libs/forms/builders/UpdateActionBuilder.ts

The actual fix was on the BE https://github.com/Demagog2/demagog/pull/1438

Improve form to resist 500 from BE

---

assets/styles/tailwind.css
components/admin/sources/statements/AdminStatementComments.tsx
libs/comments/text.ts
package-lock.json
package.json

Highlight links in the comments

---

components/admin/sources/AdminSourceStatements.tsx

Also added condition to not show quotation marks in case there is no quote, as there was one like that and it did not look good.

Fixed rear quotation mark

---

components/article/ArticleSegments.tsx
components/statement/Item.tsx

I changed also width of debate stats because on some screen sizes it didnt look good and the speaker avatar was too big

Statement listing is wider

---

assets/styles/campaign.scss
assets/styles/custom_variables.scss
assets/styles/responsive/font-size.scss
assets/styles/statement/_detail.scss
components/article/ArticleResponsivePerex.tsx
components/article/Item.tsx
components/article/SingleStatementArticlePreview.tsx

Closes https://github.com/Demagog2/demagog-frontend/issues/889

Add fs-9 and replace font-size: 12px

---

components/admin/articles/AdminArticleForm.tsx

Needs to be fixed: 
When changes made in the perex, it does not show the 'Upraveno' label, it appears only after refreshing the webpage.

Changes in article perex save into local storage

---

components/admin/sources/statements/AdminAssessmentForm.tsx

Closes https://github.com/Demagog2/demagog-frontend/issues/960

Make the usage of form state more defensive

---

components/admin/forms/Multiselect.tsx
components/admin/forms/Spinner.tsx
components/admin/forms/SubmitButton.tsx
components/admin/sources/statements/AdminAssessmentForm.tsx
components/admin/sources/statements/controls/AdminArticleTagsMultiselect.tsx
components/admin/sources/statements/controls/AdminEvaluationStatusControl.tsx
components/admin/sources/statements/controls/AdminSourceSpeakerControl.tsx
components/admin/sources/statements/controls/AdminTagsMultiselect.tsx
components/admin/sources/statements/hooks/auto-save-form-machine.ts
libs/sources/machines/auto-save-machine.ts

https://github.com/user-attachments/assets/6d8fcbaf-6794-428d-8c98-f7078d196a88

Implement auto save for admin assessment form

---

assets/styles/article/_redesign.scss

Fix embedded image size

---

app/(admin)/beta/admin/article-tags/[slug]/edit/page.tsx
app/(admin)/beta/admin/article-tags/[slug]/page.tsx
app/(admin)/beta/admin/article-tags/actions.ts
app/(admin)/beta/admin/article-tags/new/page.tsx
app/(admin)/beta/admin/article-tags/page.tsx
app/(admin)/beta/admin/tags/[slug]/edit/page.tsx
components/admin/article-tags/AdminArticleTagDeleteDialog.tsx
components/admin/article-tags/AdminArticleTagForm.tsx
components/admin/forms/SwitchField.tsx
libs/article-tags/schema.ts

I have just one problem, the Order data does not work properly. Whatever value i save in the order data it renders 0. The rest works well.

Create add new article tag form

---

components/admin/article-tags/AdminArticleTagDeleteDialog.tsx
components/admin/articles/AdminArticleDeleteDialog.tsx
components/admin/images/AdminImageDeleteDialog.tsx
components/admin/layout/dialogs/AdminDeleteDialog.tsx
components/admin/media-personalities/AdminMediaPersonalityDeleteDialog.tsx
components/admin/media/AdminMediumDeleteDialog.tsx
components/admin/sources/statements/AdminStatementDeleteDialog.tsx
components/admin/users/AdminUserDeleteDialog.tsx

The common parts were extracted to a reusable component.

Unify deleting dialogs

---

app/(admin)/beta/admin/articles/actions.ts
components/admin/articles/AdminArticleForm.tsx

The condition was inverted, so we were logging the good cases in case of the bad ones.

Improve the form logging

---

app/(admin)/beta/admin/sources/[slug]/stats/page.tsx
components/admin/sources/AdminSourceHeader.tsx
components/admin/sources/AdminSourceHostStatsChart.tsx
libs/flags.ts
package-lock.json
package.json

Add source stats to the admin

---

components/article/ArticleQuote.tsx

New block quote data displaying in article and statement

---

components/admin/articles/segments/AdminArticleQuote.tsx
components/article/ArticleQuote.tsx
components/article/BlockQuoteMetadata.tsx

Displays new block quote fields in admin article detail

---

package-lock.json

Reverts Demagog2/demagog-frontend#1082

Revert "Bump typescript from 5.7.3 to 5.8.2"

---

app/(main)/tags/facebook/page.tsx
components/admin/sources/statements/AdminStatementActivities.tsx

I also added styling for activities in admin when there is no activity yet.

Numerical pagination on facebook cooperation page

---

app/(main)/statements/[slug]/page.tsx
components/statement/StatementHeader.tsx

TODO - needs to be checked with the team wheather we want to have the packman everywhere on statements or just in the statement detail

Packman icon added to statements

---

components/admin/forms/Multiselect.tsx
components/admin/layout/AdminBadge.tsx

We have to use the pointer event to override the combobox.

Fix issue with AdminBadge

---

components/admin/articles/AdminArticleIllustrationInput.tsx
libs/images/schema.ts
pages/api/proxy-image.ts

Closes https://github.com/Demagog2/demagog-frontend/issues/1281
Closes https://github.com/Demagog2/demagog-frontend/issues/1299

Fix issues with cropping article illustration images

---

libs/images/path.ts

We have to fix mobile version now, but at least desktop looks normal

Adjust small article image preview image size

---

libs/ck-plugins/block-quote-2/block-quote-2-plugin.tsx
libs/ck-plugins/box/box.ts
libs/ck-plugins/embed.ts
package-lock.json
package.json

Reverts Demagog2/demagog-frontend#1463

Revert "Bump ckeditor to latest version"
